name: STRONG
channels:
    - bioconda
    - anaconda
    - conda-forge
dependencies:
    - snakemake >=5.5.4
    - python
    - biopython
    - bowtie2 
    - samtools
    - prodigal
    - spades
    - blast
    - concoct
    - mafft
    - trimal
    - fasttree
    - gfapy
    - future
    - pysam
    - pygam
    - statsmodels
    - pathos
    - ete3
    - bedtools
    - cmake
    - matplotlib
    - numpy
    - pandas
    - networkx
    - sklearn
    - libreadline-dev
    - libbz2-dev


