name: STRONG
channels:
    - bioconda
    - anaconda
    - r
    - conda-forge 
dependencies:
    - snakemake
    - python
    - biopython
    - bowtie2 
    - samtools
    - prodigal
    - spades
    - blast
    - concoct
    - mafft
    - trimal
    - fasttree
    - gfapy
    - future
    - pysam
    - pygam
    - statsmodels
    - pathos
    - ete3
    - bedtools
    - cmake
    - matplotlib
    - numpy=1.16.0
    - pandas>=0.24.0
    - networkx>=2.4
    - scikit-learn
    - bam-readcount
    - seaborn  
    - poppler 
    - emboss
    - r-base>=3.6.3
    - r-ggplot2>=3.3.2
    - r-getopt
    - r-reshape
    - r-reshape2
    - r-stringr 
    - gtdbtk>=1.2.0 
    - bioconductor-ggtree
    - r-wesanderson
    - libiconv
