name: STRONG
channels:
    - bioconda
    - anaconda
    - r
    - conda-forge 
dependencies:
    - snakemake
    - python
    - metabat2
    - biopython
    - bowtie2 
    - samtools
    - prodigal
    - blast
    - concoct
    - mafft
    - trimal
    - fasttree
    - gfapy
    - future
    - pysam
    - pygam
    - statsmodels
    - pathos
    - ete3
    - bedtools
    - cmake
    - matplotlib
    - numpy=1.16.0
    - pandas>=0.24.0
    - networkx>=2.4
    - scikit-learn
    - bam-readcount
    - seaborn  
    - poppler 
    - emboss
    - r-base=4.0.2
    - r-ggplot2=3.3.2
    - r-ape=5.4
    - r-getopt=1.20.3
    - r-reshape=0.8.8
    - r-reshape2=1.4.4
    - r-stringr=1.4.0
    - r-rvcheck=0.1.8
    - gtdbtk>=1.6.0 
    - bioconductor-ggtree=2.2.1
    - bioconductor-treeio=1.12.0
    - r-wesanderson
    - libiconv
