data: /mnt/gpfs/Hackathon/SyntheticCommunity  # path to data folder
cog_database: /home/sebr/seb/Database/rpsblast_cog_db/Cog
soft: /home/sergei/cog_tools
concoct_contig_size: 1000
read_length: 150
assembly: 
    assembler: spades
    k: [21,33,55]
    mem: 2000
    threads: 24
    dir: /home/sergei/cog_tools/spades/bin
    groups: ['*']
desman:
    execution: 1
    nb_haplotypes: 10
    nb_repeat: 5
