data: /mnt/gpfs/Hackathon/SyntheticCommunity  # path to data folder
cog_database: /home/sebr/seb/Database/rpsblast_cog_db/Cog
soft: "/home/sergei/cog_tools"
concoct_contig_size: 1000
read_length: 150
assembly: 
    k: 55
    assembler: spades
    dir: /home/sergei/cog_tools/spades/bin
    groups: ['*']
